# based threath on golang
FROM golang:1.21 As build

# create work folder
WORKDIR /app

# Copy dependencies and they hesh
COPY go.mod go.sum ./

# Download this dependencies locally
RUN go mod download

# Copied project to container
COPY . .

# build our app to MAIN
RUN CGO_ENABLED=0 go build -o main

# And, finally, runtime images
FROM gcr.io/distroless/static-debian12:latest-amd64

# take App Version from VERSION file in directory of project
ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION

# Copied from image above our MAIN file to DIR
COPY --from=build /app/main /catgpt/

# work directory with our app
WORKDIR /catgpt

# forward port to 9090
EXPOSE 8080 9090

# Finally finally=) start our app!
CMD [ "./main" ]
