name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*' # Срабатывать только при пуше тегов

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Yandex Container Registry
      run: |
        docker login -u ${{ secrets.YCR_USERNAME }} -p ${{ secrets.YCR_PASSWORD }} registry.yandexcloud.net
      env:
        YCR_USERNAME: ${{ secrets.YCR_USERNAME }}
        YCR_PASSWORD: ${{ secrets.YCR_PASSWORD }}

    - name: Get the tag name
      id: version
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t registry.yandexcloud.net/${{ github.repository }}:${{ steps.version.outputs.TAG_NAME }} -f Dockerfile.build .
        docker push registry.yandexcloud.net/${{ github.repository }}:${{ steps.version.outputs.TAG_NAME }}
