- name: Read version from VERSION file
  run: |
    export APP_VERSION=$(cat VERSION)
    echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
  shell: bash

  - name: Build and push Docker image
  run: |
    docker buildx create --use
    docker buildx build -t registry.yandexcloud.net/${{ github.repository }}:$APP_VERSION -f Dockerfile.build .
    docker push registry.yandexcloud.net/${{ github.repository }}:$APP_VERSION
  env:
    APP_VERSION: ${{ env.APP_VERSION }}