name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read version from VERSION file
      run: |
        export APP_VERSION=$(cat VERSION)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Login to Yandex Container Registry
      run: |
        docker login -u ${{ secrets.YA_USERNAME }} -p ${{ secrets.YA_PASSWORD }} cr.yandex
      env:
        YCR_USERNAME: ${{ secrets.YA_USERNAME }}
        YCR_PASSWORD: ${{ secrets.YA_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t cr.yandex/crps7t5p470s5a5oh5jl/gptcat:$APP_VERSION -f Dockerfile.build .
        docker push cr.yandex/crps7t5p470s5a5oh5jl/gptcat:$APP_VERSION
      env:
        APP_VERSION: ${{ env.APP_VERSION }}
