name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read version from VERSION file
      run: |
        export APP_VERSION=$(cat ./catgpt/VERSION)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Login to Yandex Container Registry
      run: |
        docker login \
        --username ${{ secrets.YA_USERNAME }} \
        --password ${{ secrets.YA_PASS }} \
        cr.yandex
      env:
        YA_USERNAME: ${{ secrets.YA_USERNAME }}
        YA_PASSWORD: ${{ secrets.YA_PASSWORD }}
    - name: List files
      run: ls -la ./catgpt
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t cr.yandex/${{ secrets.YA_REGISTRY }}/gptcat:latest -f catgpt/dockerfile catgpt/
        docker buildx push cr.yandex/${{ secrets.YA_REGISTRY }}/gptcat:{$APP_VERSION}
      env:
        APP_VERSION: ${{ env.APP_VERSION }}
